### ISSUE TITLE
qemoo upstream

### ISSUE THREAD

**Issue by betcher** [AKotov-dev/gqemoo#1]
https://abf.io/import/qemoo - project git

https://abf.io/betcher_/qemoo - just a working clone

**Comment by AKotov-dev** [comment]
Fixed, thanks. :) I will disable this `Issues`, as I have already done in other projects. The case is related to spam attacks through the GitHub notification service. You and I can discuss it perfectly directly in the forum. I apologize for the inconvenience.

Sincerely, Alex
